apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: myweb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: myapp
  maxUnavailable: 1
  selector:
    matchLabels:
      app: myapp
